ALTER TABLE hotels ADD COLUMN IF NOT EXISTS system_prompt TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS smtp_port INTEGER DEFAULT 587;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS smtp_user TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS smtp_pass TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS smtp_from TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{}';
